//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOS_Material
    {
        public int gos_id { get; set; }
        public string material { get; set; }
        public Nullable<int> quantity { get; set; }
        public string unit { get; set; }
        public Nullable<float> unit_price { get; set; }
    
        public virtual GO GO { get; set; }
    }
}
