//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Head_Office_Expenses
    {
        public int expense_id { get; set; }
        public string description { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<int> bill_no { get; set; }
        public Nullable<int> entered_by { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
