//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_From_Stock
    {
        public int issue_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> site_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Site Site { get; set; }
    }
}
