//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Money_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Money_Request()
        {
            this.Money_Request_Status = new HashSet<Money_Request_Status>();
        }
    
        public int request_id { get; set; }
        public int site_id { get; set; }
        public string description { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<System.DateTime> requested_on { get; set; }
        public Nullable<System.TimeSpan> requested_at { get; set; }
        public Nullable<int> approved_by { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Money_Request_Status> Money_Request_Status { get; set; }
        public virtual Site Site { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
