//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Money_Request_Status
    {
        public int request_id { get; set; }
        public int site_id { get; set; }
        public string status { get; set; }
    
        public virtual Money_Request Money_Request { get; set; }
    }
}
