//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petty_Cash
    {
        public int petty_cash_id { get; set; }
        public int request_id { get; set; }
        public int site_id { get; set; }
        public Nullable<int> deliverer { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<float> balance { get; set; }
        public string status { get; set; }
    
        public virtual Money_Request Money_Request { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
