//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_InTo_Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_InTo_Stock()
        {
            this.Purchase_InTo_Stock_Material = new HashSet<Purchase_InTo_Stock_Material>();
        }
    
        public int purchase_id { get; set; }
        public string dealer { get; set; }
        public Nullable<float> total_amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> bill_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_InTo_Stock_Material> Purchase_InTo_Stock_Material { get; set; }
    }
}
