//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_InTo_Stock_Material
    {
        public int material_id { get; set; }
        public int purchase_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<float> unit_price { get; set; }
    
        public virtual Purchase_InTo_Stock Purchase_InTo_Stock { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
