//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Other_Expenses
    {
        public int site_expense_id { get; set; }
        public int site_id { get; set; }
        public string description { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<int> bill_no { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
