//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Material_Report
    {
        public int site_id { get; set; }
        public System.DateTime date { get; set; }
        public int material_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public string unit { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
