//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Note
    {
        public int site_id { get; set; }
        public int note_id { get; set; }
        public string note { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
