//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Attendance
    {
        public int staff_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<bool> attendance { get; set; }
        public Nullable<System.TimeSpan> time_in { get; set; }
        public Nullable<System.TimeSpan> time_out { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
