//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.Issue_From_Stock_Material = new HashSet<Issue_From_Stock_Material>();
            this.Purchase_InTo_Stock_Material = new HashSet<Purchase_InTo_Stock_Material>();
            this.Site_Material_Report = new HashSet<Site_Material_Report>();
        }
    
        public int material_id { get; set; }
        public string material_name { get; set; }
        public string brand { get; set; }
        public Nullable<int> quantity { get; set; }
        public string unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue_From_Stock_Material> Issue_From_Stock_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_InTo_Stock_Material> Purchase_InTo_Stock_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site_Material_Report> Site_Material_Report { get; set; }
    }
}
